export const MODULES = {
  DASHBOARD: 'Dashboard',
  BOOKINGS: 'Bookings',
  CALENDAR: 'Calendar',
  NOTIFICATIONS: 'Notifications',
  MEMBERS: 'Members',
  ROOMS: 'Rooms',
  ROOM_TYPES: 'Room Types',
  ROOM_BOOKINGS: 'Room Bookings',
  HALLS: 'Halls',
  HALL_BOOKINGS: 'Hall Bookings',
  LAWNS: 'Lawns',
  LAWN_CATEGORIES: 'Lawn Categories',
  LAWN_BOOKINGS: 'Lawn Bookings',
  PHOTOSHOOT: 'Photoshoot',
  PHOTOSHOOT_BOOKINGS: 'Photoshoot Bookings',
  SPORTS: 'Sports',
  ACCOUNTS: 'Accounts',
  AFFILIATED_CLUBS: 'Affiliated Clubs',
  CONTENTS: 'Contents',
  ADMIN_RESERVATIONS: 'Admin Reservations',
  MESSING: 'Messing',
  ADMINS: 'Admins',
  FEEDBACK: 'Feedback',
  SEARCH: 'Search',
  ROOM_REPORTS: 'Room Reports',
  HALL_REPORTS: 'Hall Reports',
  PHOTOSHOOT_REPORTS: 'Photoshoot Reports',
} as const;

export type ModuleKey = (typeof MODULES)[keyof typeof MODULES];

export type ModulePermissionAction = 'read' | 'create' | 'update' | 'delete';

const CRUD: ModulePermissionAction[] = ['read', 'create', 'update', 'delete'];

export const MODULE_CAPABILITIES: Record<ModuleKey, ModulePermissionAction[]> = {
  [MODULES.DASHBOARD]: ['read'],
  [MODULES.BOOKINGS]: ['read'],
  [MODULES.CALENDAR]: ['read'],
  [MODULES.NOTIFICATIONS]: ['read', 'create', 'delete'],
  [MODULES.MEMBERS]: CRUD,
  [MODULES.ROOMS]: CRUD,
  [MODULES.ROOM_TYPES]: CRUD,
  [MODULES.ROOM_BOOKINGS]: CRUD,
  [MODULES.HALLS]: CRUD,
  [MODULES.HALL_BOOKINGS]: CRUD,
  [MODULES.LAWNS]: CRUD,
  [MODULES.LAWN_CATEGORIES]: CRUD,
  [MODULES.LAWN_BOOKINGS]: CRUD,
  [MODULES.PHOTOSHOOT]: CRUD,
  [MODULES.PHOTOSHOOT_BOOKINGS]: CRUD,
  [MODULES.SPORTS]: CRUD,
  [MODULES.ACCOUNTS]: CRUD,
  [MODULES.AFFILIATED_CLUBS]: CRUD,
  [MODULES.CONTENTS]: CRUD,
  [MODULES.ADMIN_RESERVATIONS]: ['read', 'update'],
  [MODULES.MESSING]: CRUD,
  [MODULES.ADMINS]: CRUD,
  [MODULES.FEEDBACK]: ['read'],
  [MODULES.SEARCH]: ['read'],
  [MODULES.ROOM_REPORTS]: ['read'],
  [MODULES.HALL_REPORTS]: ['read'],
  [MODULES.PHOTOSHOOT_REPORTS]: ['read'],
};
